version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8080"
      - "49152-65535"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # CRUCIAL CHANGE: Mounted to /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
